-- PROP_STAT 값 분포 확인용 (취소 상태코드 파악)
-- 주문확정일 기준 최근 3개월

SELECT
  p.PROP_STAT AS PROP_STAT,
  COUNT(*) AS cnt
FROM
  PROP p
  INNER JOIN PROP_ITEM pi ON pi.PROP_USID = p.PROP_USID
    AND pi.DEL_YN = 0
  INNER JOIN PARTNER pa ON pa.PARTNER_USID = p.PARTNER_USID
WHERE
  p.DEL_YN = 0
  AND p.CONFIRMED_TS >= DATE_SUB(CURDATE(), INTERVAL 3 MONTH)
  AND pa.COMPANY != '렌트리 안심구독(TPS)'
GROUP BY p.PROP_STAT
ORDER BY cnt DESC
